networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
      - server
    entrypoint: /client
    environment:
      - CLI_ID=1
      - LOGGING_LEVEL=DEBUG
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    profiles: [ "prod" ]
  client2:
    container_name: client2
    depends_on:
      - server
    entrypoint: /client
    environment:
      - CLI_ID=2
      - LOGGING_LEVEL=DEBUG
      - NOMBRE=Marcos
      - APELLIDO=Lorca
      - DOCUMENTO=30404465
      - NACIMIENTO=1999-03-12
      - NUMERO=7575
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    profiles: [ "prod" ]
  client3:
    container_name: client3
    depends_on:
      - server
    entrypoint: /client
    environment:
      - CLI_ID=3
      - LOGGING_LEVEL=DEBUG
      - NOMBRE=Agustin
      - APELLIDO=Liones
      - DOCUMENTO=40902465
      - NACIMIENTO=1919-02-17
      - NUMERO=6574
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    profiles: [ "prod" ]
  client4:
    container_name: client4
    depends_on:
      - server
    entrypoint: /client
    environment:
      - CLI_ID=4
      - LOGGING_LEVEL=DEBUG
      - NOMBRE=Lionel
      - APELLIDO=Santiago
      - DOCUMENTO=30903464
      - NACIMIENTO=1995-03-17
      - NUMERO=7577
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    profiles: [ "prod" ]
  client5:
    container_name: client5
    depends_on:
      - server
    entrypoint: /client
    environment:
      - CLI_ID=5
      - LOGGING_LEVEL=DEBUG
      - NOMBRE=Agustina
      - APELLIDO=Roldan
      - DOCUMENTO=30911465
      - NACIMIENTO=1999-11-17
      - NUMERO=1114
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    profiles: [ "prod" ]
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
    profiles: [ "prod", "dev" ]
  netcat:
    image: alpine
    profiles: [ "dev" ]
    tty: true
    networks:
      - testing_net
    depends_on:
      - server
version: '3.9'
