networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
      - server
    entrypoint: /client
    environment:
      - CLI_ID=1
      - LOGGING_LEVEL=DEBUG
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    profiles: [ "prod" ]
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
    profiles: [ "prod", "dev" ]
  netcat:
    image: alpine
    profiles: [ "dev" ]
    tty: true
    networks:
      - testing_net
    depends_on:
      - server
version: '3.9'
