networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    profiles:
    - prod
    volumes:
    - ./client/config.yaml:/config.yaml
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    profiles:
    - prod
    volumes:
    - ./client/config.yaml:/config.yaml
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    profiles:
    - prod
    volumes:
    - ./client/config.yaml:/config.yaml
  client4:
    container_name: client4
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=4
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    profiles:
    - prod
    volumes:
    - ./client/config.yaml:/config.yaml
  client5:
    container_name: client5
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=5
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    profiles:
    - prod
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
version: '3.9'
